change2aa

diff --git a/.github/workflows/betterer.yml b/.github/workflows/betterer.yml
--- a/.github/workflows/betterer.yml
+++ b/.github/workflows/betterer.yml
@@ -20,28 +20,14 @@ jobs:
         run: |
           yarn betterer ci | sed -r "s/\x1B\[(([0-9]{1,2})?(;)?([0-9]{1,2})?)?[m,K,H,f,J]//g" | tee betterer-log.txt
           result="${PIPESTATUS[0]}"
+          error_message="Error: ❌ Shiet, Betterer reports more issues with TypeScript!\n"
+          what_to_do_message="Please fix the mentioned TypeScript issues.\n"
+          how_to_update_betterer_message="If you do not have the capacity to fix the issues. Please add \"betterer:update\" comment to this PR, and CI bot will update the file containing all TypeScript issues and commit it to this PR."
           echo "::set-output name=result::$result"
-      - name: Add comment
-        uses: actions/github-script@v4
-        env:
-          BETTERER_RESULT: ${{ steps.run_betterer.outputs.result }}
-        with:
-          script: |
-            let shouldPrint = false
-            const result = `${process.env.BETTERER_RESULT}`
-            console.log(`result ${result}`)
-            console.log(`context ${JSON.stringify(context, null, 2)}`)
-            const errorMessage = `❌ Shiet, Betterer reports more issues with TypeScript!`
-            const instructions = `\n\nPlease fix those issues to make our code better.`
-            const updateInstructions = `\n\nIf however, you think you can't fix those issues right now, add comment with \`betterer:update\` and bot will do that for you!`
-            if (result !== '0') {
-              github.issues.createComment({
-                issue_number: context.issue.number,
-                owner: context.repo.owner,
-                repo: context.repo.repo,
-                body: `${errorMessage}`,
-              });
-            }
-#      - name: Incremental code quality check
-#        run: yarn betterer ci
+          if [ "$result" = "0" ]; then
+            echo "Info: Typescript check is ok!"
+          else
+            echo "$error_message $what_to_do_message $how_to_update_betterer_message"
+            exit 1
+          fi
 
